apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: go-template
  title: Go Template
  description: Create a service using Go
  tags:
    - recommended
    - go

spec:
  owner: alexdunne/go-template
  type: service

  parameters:
    - title: Backstage information
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

    - title: Repo configuration
      required:
        - repoTopics
        - repoAutoLinking
      properties:
        repoTopics:
          title: Repository Topics
          type: array
          items:
            type: string
          default:
            - "go"
            - "software-engineering"
            - "core-software-team"
          ui:options:
            orderable: false
        repoAutoLinking:
          title: Repository Autolinking
          type: object
          required:
            - keyPrefix
            - urlTemplate
          properties:
            keyPrefix:
              type: string
              title: Key Prefix
              description: "JIRA-123 the prefix would be JIRA-"
            urlTemplate:
              type: string
              title: URL Template
              description: "https://jira.atlassian.net/browse/JIRA-123 the URL Template would be https://jira.atlassian.net/browse/JIRA-<num>"

    - title: Codefresh configuration
      required:
        - useCodefresh
      properties:
        useCodefresh:
          title: Set up Codefresh pipeline
          type: string
          enum:
            - "Yes"
            - "No"
          default: "Yes"
        codefreshTags:
          title: Codefresh tags
          type: array
          items:
            type: string
          default:
            - "golang"
          ui:options:
            orderable: false

    - title: Codacy configuration
      required:
        - useCodacy
      properties:
        useCodacy:
          title: Set up Codacy pipeline
          type: string
          enum:
            - "Yes"
            - "No"
          default: "Yes"

    - title: Terraform configuration
      required:
        - useTerraform
      properties:
        useTerraform:
          title: Set up Terraform pipeline
          type: string
          enum:
            - "Yes"
            - "No"
          default: "Yes"

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}
